### ISSUE TITLE
Clean up serialization module code

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/DistributedFactorGraphs.jl#44]
How should we do this?

https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/master/src/services/AbstractDFG.jl#L19-L26

**Comment by dehann** [comment]
Oh, yeah that ... will have to think on that a bit more.  Shall we target DFG v0.2.0 for a decision here?

**Comment by dehann** [comment]
Ideally we don't want to have to "register" anything and just allow dispatch to find the required converters.  I recall we were trying to make this work without and weren't able to resolve it at the time.  I think the issue was module name discovery for some reason.  Looks like you always just consider `Main` which feels like the right way to do it -- think that is further than what I could get working previously.

**Comment by Affie** [comment]
@GearsAD or @dehann, with reference to what is this? the code link is broken

**Comment by Affie** [comment]
It was getSerializationModule
