### ISSUE TITLE
should lsTypes and lsfTypes just return a list of the types

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#465]
eg. [PriorPose2, Pose2Pose2, Point2Point2, ...]

It is currently a dictionary with type::Symbol=>Vector{type::String} which is a bit strange
```julia
Dict{Symbol, Array{String,1}} with 2 entries
:TestFunctorInferenceType1 => 
    Vector{String} with 1 element
        "TestFunctorInferenceType1"
:TestFunctorSingleton => 
    Vector{String} with 1 element
        "TestFunctorSingleton"
```

**Comment by dehann** [comment]
HI, the idea a while back was it would return the types and which factor labels were of that type (hence the dictionary).  This was reasonable since the function lsType already had the labels available during the calculation, but no longer fits the verbNoun 100%.  So how about if we write the main function as `lsTypesDict` and then a simplified `lsTypes` more like a wrapper that only returns a list of types?

**Comment by dehann** [comment]
should probably make ti:
```julia
Dict{Symbol,Vector{Symbol}}
```

and `lsTypes(args...; kwargs...) = keys(lsTypesDict(args...; kwargs...)) |> collect`
